# Generated by Django 5.2.17 on 2026-09-02 11:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_visit_information_and_media_rights'),
        ('discovery', '0001_search_document'),
        ('sources', '0005_institution_qualification_and_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFeatureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.CharField(max_length=32)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_feature_snapshots', to='catalog.exhibition')),
            ],
            options={
                'ordering': ('exhibition_id', '-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ContentFeatureAssertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis', models.CharField(choices=[('MEDIA_GROUP', 'Media group'), ('MEDIA_DETAIL', 'Media detail'), ('THEME', 'Theme'), ('MOOD', 'Mood'), ('EXPERIENCE', 'Experience'), ('SPACE_TYPE', 'Space type'), ('EVENT_FORMAT', 'Event format')], max_length=16)),
                ('value', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Feature value must be a 1-64 character uppercase stable code.', regex='^[A-Z0-9][A-Z0-9_:-]{0,63}$')])),
                ('evidence_kind', models.CharField(choices=[('DIRECT', 'Direct'), ('DERIVED', 'Derived')], max_length=16)),
                ('rule_version', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_feature_assertions', to='sources.sourcerecord')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assertions', to='discovery.contentfeaturesnapshot')),
            ],
            options={
                'ordering': ('snapshot_id', 'axis', 'value', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='contentfeaturesnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('exhibition',), name='discovery_unique_current_feature_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='contentfeatureassertion',
            constraint=models.UniqueConstraint(fields=('snapshot', 'axis', 'value'), name='discovery_unique_snapshot_feature'),
        ),
        migrations.AddConstraint(
            model_name='contentfeatureassertion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('evidence_kind', 'DIRECT'), ('rule_version', '')), models.Q(('evidence_kind', 'DERIVED'), models.Q(('rule_version', ''), _negated=True)), _connector='OR'), name='discovery_feature_evidence_rule'),
        ),
    ]
