# Generated by Django 5.2.17 on 2026-08-31 12:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, max_length=128)),
                ('source_record_id', models.CharField(blank=True, max_length=255)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=16)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_records', to='catalog.exhibition')),
                ('ingestion_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_records', to='sources.ingestionrun')),
            ],
            options={
                'ordering': ('-checked_at', '-id'),
                'indexes': [models.Index(fields=['exhibition', 'checked_at'], name='catalog_verification_lookup')],
                'constraints': [models.UniqueConstraint(fields=('exhibition', 'ingestion_run'), name='catalog_unique_exhibition_verification_run')],
            },
        ),
    ]
