# Generated by Django 5.2.17 on 2026-09-01 12:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_change_history'),
        ('sources', '0005_institution_qualification_and_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video')], max_length=8)),
                ('role', models.CharField(choices=[('POSTER', 'Poster'), ('SPACE_PHOTO', 'Space photo'), ('ARTWORK_IMAGE', 'Artwork image'), ('PERSON_PHOTO', 'Person photo'), ('VIDEO_THUMBNAIL', 'Video thumbnail'), ('AUDIO', 'Audio'), ('FULL_VIDEO', 'Full video')], max_length=24)),
                ('origin_url', models.URLField(max_length=2048, validators=[django.core.validators.URLValidator(schemes=('https',))])),
                ('source_page_url', models.URLField(max_length=2048, validators=[django.core.validators.URLValidator(schemes=('https',))])),
                ('exhibition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='catalog.exhibition')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='catalog.institution')),
                ('source_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='sources.sourcerecord')),
            ],
            options={
                'ordering': ('exhibition_id', 'institution_id', 'role', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MediaRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_status', models.CharField(choices=[('REUSE_ALLOWED', 'Reuse allowed'), ('LINK_ONLY', 'Link only'), ('RIGHTS_UNKNOWN', 'Rights unknown'), ('UNAVAILABLE_OR_WITHDRAWN', 'Unavailable or withdrawn')], max_length=32)),
                ('rights_holder', models.CharField(blank=True, max_length=255)),
                ('license_name', models.CharField(blank=True, max_length=255)),
                ('credit_line', models.TextField(blank=True)),
                ('display_allowed', models.BooleanField(default=False)),
                ('copy_allowed', models.BooleanField(default=False)),
                ('cache_allowed', models.BooleanField(default=False)),
                ('transform_allowed', models.BooleanField(default=False)),
                ('hotlink_allowed', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=True)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rights_history', to='catalog.mediaasset')),
                ('source_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_rights_records', to='sources.sourcerecord')),
            ],
            options={
                'ordering': ('asset_id', '-reviewed_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PriceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('UNKNOWN', 'Unknown')], max_length=16)),
                ('category', models.CharField(blank=True, choices=[('STANDARD', 'Standard admission'), ('DISCOUNT', 'Discount'), ('PROGRAM', 'Program')], max_length=16)),
                ('audience', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('amount_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_free', models.BooleanField(blank=True, null=True)),
                ('is_standard_adult_admission', models.BooleanField(default=False)),
                ('details', models.TextField(blank=True)),
                ('exhibition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='catalog.exhibition')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='catalog.institution')),
                ('source_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='sources.sourcerecord')),
            ],
            options={
                'ordering': ('exhibition_id', 'institution_id', 'category', 'audience', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ReservationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation_type', models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('REQUIRED', 'Required'), ('RECOMMENDED', 'Recommended'), ('TIMED_ENTRY', 'Timed entry'), ('ON_SITE', 'On site'), ('FIRST_COME', 'First come'), ('PROGRAM_ONLY', 'Program only'), ('UNKNOWN', 'Unknown')], max_length=16)),
                ('official_url', models.URLField(blank=True, max_length=2048, validators=[django.core.validators.URLValidator(schemes=('https',))])),
                ('guidance', models.TextField(blank=True)),
                ('exhibition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='catalog.exhibition')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='catalog.institution')),
                ('source_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='sources.sourcerecord')),
            ],
            options={
                'ordering': ('exhibition_id', 'institution_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SensoryNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('CONFIRMED_POSITIVE', 'Confirmed positive'), ('CONFIRMED_NEGATIVE', 'Confirmed negative'), ('UNKNOWN', 'Unknown')], max_length=24)),
                ('details', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('LOUD_SOUND', 'Loud sound'), ('SUDDEN_SOUND', 'Sudden sound'), ('FLASHING_LIGHTS', 'Flashing lights'), ('DARK_SPACE', 'Dark space'), ('NARROW_OR_ENCLOSED_SPACE', 'Narrow or enclosed space')], max_length=32)),
                ('exhibition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='catalog.exhibition')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='catalog.institution')),
                ('source_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='sources.sourcerecord')),
            ],
            options={
                'ordering': ('exhibition_id', 'institution_id', 'kind', 'id'),
            },
        ),
        migrations.CreateModel(
            name='VisitDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OFFICIAL', 'Official'), ('UNKNOWN', 'Unknown')], max_length=16)),
                ('minimum_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('exhibition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='catalog.exhibition')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='catalog.institution')),
                ('source_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='sources.sourcerecord')),
            ],
            options={
                'ordering': ('exhibition_id', 'institution_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AccessibilityFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('CONFIRMED_POSITIVE', 'Confirmed positive'), ('CONFIRMED_NEGATIVE', 'Confirmed negative'), ('UNKNOWN', 'Unknown')], max_length=24)),
                ('details', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('WHEELCHAIR_ACCESS', 'Wheelchair access'), ('MOBILITY_ACCESS', 'Mobility access'), ('CAPTIONS', 'Captions'), ('SIGN_LANGUAGE', 'Sign language'), ('AUDIO_DESCRIPTION', 'Audio description'), ('AGE_CONDITION', 'Age condition')], max_length=24)),
                ('exhibition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='catalog.exhibition')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='catalog.institution')),
                ('source_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='sources.sourcerecord')),
            ],
            options={
                'ordering': ('exhibition_id', 'institution_id', 'kind', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('exhibition__isnull', False), ('institution__isnull', True)), models.Q(('exhibition__isnull', True), ('institution__isnull', False)), _connector='OR'), name='catalog_access_target_xor'), models.CheckConstraint(condition=models.Q(models.Q(('state', 'UNKNOWN'), _negated=True), ('details', ''), _connector='OR'), name='catalog_access_unknown_empty'), models.UniqueConstraint(condition=models.Q(('exhibition__isnull', False)), fields=('exhibition', 'source_record', 'kind'), name='catalog_access_source_exhibition'), models.UniqueConstraint(condition=models.Q(('institution__isnull', False)), fields=('institution', 'source_record', 'kind'), name='catalog_access_source_institution')],
            },
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('exhibition__isnull', False), ('institution__isnull', True)), models.Q(('exhibition__isnull', True), ('institution__isnull', False)), _connector='OR'), name='catalog_media_target_xor'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.UniqueConstraint(fields=('source_record', 'role', 'origin_url'), name='catalog_media_source_role_url'),
        ),
        migrations.AddConstraint(
            model_name='mediarights',
            constraint=models.UniqueConstraint(fields=('asset', 'source_record'), name='catalog_media_rights_evidence'),
        ),
        migrations.AddConstraint(
            model_name='mediarights',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('asset',), name='catalog_media_one_current_rights'),
        ),
        migrations.AddConstraint(
            model_name='mediarights',
            constraint=models.CheckConstraint(condition=models.Q(('policy_status', 'REUSE_ALLOWED'), models.Q(('cache_allowed', False), ('copy_allowed', False), ('display_allowed', False), ('hotlink_allowed', False), ('transform_allowed', False)), _connector='OR'), name='catalog_media_nonreuse_denied'),
        ),
        migrations.AddConstraint(
            model_name='mediarights',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('policy_status', 'REUSE_ALLOWED'), _negated=True), models.Q(models.Q(('rights_holder', ''), _negated=True), models.Q(('license_name', ''), _negated=True), models.Q(('display_allowed', True), ('copy_allowed', True), ('cache_allowed', True), ('transform_allowed', True), ('hotlink_allowed', True), _connector='OR')), _connector='OR'), name='catalog_media_reuse_evidence'),
        ),
        migrations.AddConstraint(
            model_name='priceoption',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('exhibition__isnull', False), ('institution__isnull', True)), models.Q(('exhibition__isnull', True), ('institution__isnull', False)), _connector='OR'), name='catalog_price_target_xor'),
        ),
        migrations.AddConstraint(
            model_name='priceoption',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'CONFIRMED'), models.Q(('amount_max__isnull', True), ('amount_min__isnull', True), ('audience', ''), ('category', ''), ('currency', ''), ('details', ''), ('is_free__isnull', True), ('is_standard_adult_admission', False), ('status', 'UNKNOWN')), _connector='OR'), name='catalog_price_unknown_empty'),
        ),
        migrations.AddConstraint(
            model_name='priceoption',
            constraint=models.CheckConstraint(condition=models.Q(('amount_max__isnull', True), models.Q(('amount_max__gte', models.F('amount_min')), ('amount_min__isnull', False)), _connector='OR'), name='catalog_price_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='priceoption',
            constraint=models.UniqueConstraint(condition=models.Q(('exhibition__isnull', False)), fields=('exhibition', 'source_record', 'category', 'audience'), name='catalog_price_source_exhibition'),
        ),
        migrations.AddConstraint(
            model_name='priceoption',
            constraint=models.UniqueConstraint(condition=models.Q(('institution__isnull', False)), fields=('institution', 'source_record', 'category', 'audience'), name='catalog_price_source_institution'),
        ),
        migrations.AddConstraint(
            model_name='reservationinfo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('exhibition__isnull', False), ('institution__isnull', True)), models.Q(('exhibition__isnull', True), ('institution__isnull', False)), _connector='OR'), name='catalog_reservation_target_xor'),
        ),
        migrations.AddConstraint(
            model_name='reservationinfo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reservation_type', 'UNKNOWN'), _negated=True), models.Q(('guidance', ''), ('official_url', '')), _connector='OR'), name='catalog_reservation_unknown_empty'),
        ),
        migrations.AddConstraint(
            model_name='reservationinfo',
            constraint=models.UniqueConstraint(condition=models.Q(('exhibition__isnull', False)), fields=('exhibition', 'source_record'), name='catalog_reservation_source_exhibition'),
        ),
        migrations.AddConstraint(
            model_name='reservationinfo',
            constraint=models.UniqueConstraint(condition=models.Q(('institution__isnull', False)), fields=('institution', 'source_record'), name='catalog_reservation_source_institution'),
        ),
        migrations.AddConstraint(
            model_name='sensorynotice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('exhibition__isnull', False), ('institution__isnull', True)), models.Q(('exhibition__isnull', True), ('institution__isnull', False)), _connector='OR'), name='catalog_sensory_target_xor'),
        ),
        migrations.AddConstraint(
            model_name='sensorynotice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'UNKNOWN'), _negated=True), ('details', ''), _connector='OR'), name='catalog_sensory_unknown_empty'),
        ),
        migrations.AddConstraint(
            model_name='sensorynotice',
            constraint=models.UniqueConstraint(condition=models.Q(('exhibition__isnull', False)), fields=('exhibition', 'source_record', 'kind'), name='catalog_sensory_source_exhibition'),
        ),
        migrations.AddConstraint(
            model_name='sensorynotice',
            constraint=models.UniqueConstraint(condition=models.Q(('institution__isnull', False)), fields=('institution', 'source_record', 'kind'), name='catalog_sensory_source_institution'),
        ),
        migrations.AddConstraint(
            model_name='visitduration',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('exhibition__isnull', False), ('institution__isnull', True)), models.Q(('exhibition__isnull', True), ('institution__isnull', False)), _connector='OR'), name='catalog_duration_target_xor'),
        ),
        migrations.AddConstraint(
            model_name='visitduration',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'OFFICIAL'), models.Q(('details', ''), ('maximum_minutes__isnull', True), ('minimum_minutes__isnull', True), ('status', 'UNKNOWN')), _connector='OR'), name='catalog_duration_unknown_empty'),
        ),
        migrations.AddConstraint(
            model_name='visitduration',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_minutes__isnull', True), models.Q(('maximum_minutes__gte', models.F('minimum_minutes')), ('minimum_minutes__isnull', False)), _connector='OR'), name='catalog_duration_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='visitduration',
            constraint=models.UniqueConstraint(condition=models.Q(('exhibition__isnull', False)), fields=('exhibition', 'source_record'), name='catalog_duration_source_exhibition'),
        ),
        migrations.AddConstraint(
            model_name='visitduration',
            constraint=models.UniqueConstraint(condition=models.Q(('institution__isnull', False)), fields=('institution', 'source_record'), name='catalog_duration_source_institution'),
        ),
    ]
