# Generated by Django 5.2.17 on 2026-09-06 10:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_visit_information_and_media_rights"),
        ("sources", "0005_institution_qualification_and_promotion"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatingSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("verified_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(choices=[("CONFIRMED", "Confirmed"), ("UNKNOWN", "Unknown")], max_length=16)),
                ("kind", models.CharField(choices=[("REGULAR", "Regular weekday rule"), ("OVERRIDE", "Temporary date override")], max_length=16)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField()),
                ("weekdays", models.JSONField(blank=True, default=list)),
                ("is_open", models.BooleanField(blank=True, null=True)),
                ("opens_at", models.TimeField(blank=True, null=True)),
                ("closes_at", models.TimeField(blank=True, null=True)),
                ("details", models.TextField(blank=True)),
                ("rule_version", models.CharField(max_length=64)),
                ("exhibition", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(class)s_records", to="catalog.exhibition")),
                ("institution", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(class)s_records", to="catalog.institution")),
                ("source_record", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="%(class)s_records", to="sources.sourcerecord")),
            ],
            options={
                "ordering": ("exhibition_id", "institution_id", "effective_from", "kind", "id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=(models.Q(exhibition__isnull=False, institution__isnull=True)
                                   | models.Q(exhibition__isnull=True, institution__isnull=False)),
                        name="catalog_schedule_target_xor",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(effective_to__gte=models.F("effective_from")),
                        name="catalog_schedule_date_range",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(status="UNKNOWN", is_open__isnull=True, weekdays=[], opens_at__isnull=True, closes_at__isnull=True)
                            | models.Q(status="CONFIRMED", is_open=False, is_open__isnull=False, opens_at__isnull=True, closes_at__isnull=True)
                            | models.Q(status="CONFIRMED", is_open=True, is_open__isnull=False, opens_at__isnull=False, closes_at__isnull=False, closes_at__gt=models.F("opens_at"))
                        ),
                        name="catalog_schedule_valid_state",
                    ),
                    models.CheckConstraint(
                        condition=(models.Q(kind="REGULAR") | models.Q(kind="OVERRIDE", weekdays=[])),
                        name="catalog_schedule_valid_kind",
                    ),
                ],
            },
        ),
    ]
